language: python
python: 2.7
sudo: false
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=flake8
install:
    - pip install tox
script:
    - tox -e $TOX_ENV

notifications:
    irc:
        channels:
            - "irc.mozilla.org#services-dev"
        on_success: change
